name: Build vLLM Training Image

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths:
      - 'training/vllm/**'
      - 'docker/vllm/Dockerfile.training'
      - '.github/workflows/vllm-build-training-image.yaml'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom image tag (optional)'
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  build-training-image:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      ACCOUNT_ID: 123456789012
      IMAGE_NAME: vllm-training-tools

    steps:
      - name: Free disk space
        run: |
          echo "Disk space before cleanup:"
          df -h /
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          echo "Disk space after cleanup:"
          df -h /

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set image tag
        id: set-tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.tag }}" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAG="latest"
          else
            BRANCH=${GITHUB_REF#refs/heads/}
            SHORT_SHA=${GITHUB_SHA:0:7}
            TAG="${BRANCH}-${SHORT_SHA}"
          fi

          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV
          echo "Building with tag: ${TAG}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push training image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/vllm/Dockerfile.training
          push: true
          tags: ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:cache,mode=max

      - name: Test image dependencies
        run: |
          echo "Testing that all Python dependencies are importable..."
          docker run --rm ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            python -c "
          import torch
          import transformers
          import peft
          import bitsandbytes
          import datasets
          import accelerate
          import mlflow
          import boto3
          print('All dependencies imported successfully')
          print(f'PyTorch: {torch.__version__}')
          print(f'CUDA available: {torch.cuda.is_available()}')
          print(f'Transformers: {transformers.__version__}')
          print(f'PEFT: {peft.__version__}')
          print(f'MLflow: {mlflow.__version__}')
          "

      - name: Check image size
        run: |
          IMAGE_SIZE=$(docker images ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --format "{{.Size}}")
          echo "Image size: ${IMAGE_SIZE}"

          SIZE_BYTES=$(docker image inspect ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --format='{{.Size}}')
          SIZE_MB=$((SIZE_BYTES / 1024 / 1024))

          echo "Image size in MB: ${SIZE_MB}"

          if [ ${SIZE_MB} -gt 4096 ]; then
            echo "Warning: Image size exceeds 4GB"
          fi

      - name: Output image URI
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "vLLM training image built and pushed successfully!"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          echo "Image URI:"
          echo "${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo ""
