apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-inference-judge-large
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/mlops-on-kubernetes
    targetRevision: main
    path: infra/k8s/vllm/overlays/judge-large
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-models
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false  # Namespace already exists